// <auto-generated />
using System;
using Bussiness_Manager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bussiness_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    partial class ApplicationDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bussiness_Manager.Models.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("dstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("mobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shopId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("customerId");

                    b.HasIndex("memberId");

                    b.HasIndex("shopId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Members", b =>
                {
                    b.Property<int>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("memberId"));

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("dstatus")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("DateTime");

                    b.HasKey("memberId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("dstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("productCategory")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("qty")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<decimal?>("salePrice")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<int>("shopId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("memberId");

                    b.HasIndex("shopId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.ShopDetail", b =>
                {
                    b.Property<int>("shopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shopId"));

                    b.Property<string>("bussinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("DateTime");

                    b.Property<string>("dstatus")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("shopAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("shopDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("shopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("DateTime");

                    b.HasKey("shopId");

                    b.HasIndex("memberId");

                    b.ToTable("shopDetails");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.saleInvoice", b =>
                {
                    b.Property<int>("saleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleId"));

                    b.Property<decimal?>("balanceAmount")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("discount")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<string>("dstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<decimal?>("netAmount")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<int>("shopId")
                        .HasColumnType("int");

                    b.Property<decimal?>("totalAmount")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("saleId");

                    b.HasIndex("customerId");

                    b.HasIndex("memberId");

                    b.HasIndex("shopId");

                    b.ToTable("saleInvoices");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.saleInvoiceDetail", b =>
                {
                    b.Property<int>("sdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sdId"));

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("dstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("netAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("saleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("sdId");

                    b.HasIndex("productId");

                    b.HasIndex("saleId");

                    b.ToTable("saleInvoiceDetails");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Customer", b =>
                {
                    b.HasOne("Bussiness_Manager.Models.Members", "Members")
                        .WithMany("Customers")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Manager.Models.ShopDetail", "ShopDetail")
                        .WithMany("Customers")
                        .HasForeignKey("shopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("ShopDetail");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Product", b =>
                {
                    b.HasOne("Bussiness_Manager.Models.Members", "Members")
                        .WithMany("Products")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Manager.Models.ShopDetail", "ShopDetail")
                        .WithMany("Products")
                        .HasForeignKey("shopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("ShopDetail");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.ShopDetail", b =>
                {
                    b.HasOne("Bussiness_Manager.Models.Members", "Members")
                        .WithMany("ShopDetails")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.saleInvoice", b =>
                {
                    b.HasOne("Bussiness_Manager.Models.Customer", "Customer")
                        .WithMany("saleInvoices")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bussiness_Manager.Models.Members", "Members")
                        .WithMany("saleInvoices")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Manager.Models.ShopDetail", "ShopDetail")
                        .WithMany("saleInvoices")
                        .HasForeignKey("shopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Members");

                    b.Navigation("ShopDetail");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.saleInvoiceDetail", b =>
                {
                    b.HasOne("Bussiness_Manager.Models.Product", "Product")
                        .WithMany("saleInvoiceDetails")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bussiness_Manager.Models.saleInvoice", "SaleInvoice")
                        .WithMany("saleInvoiceDetails")
                        .HasForeignKey("saleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleInvoice");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Customer", b =>
                {
                    b.Navigation("saleInvoices");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Members", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("ShopDetails");

                    b.Navigation("saleInvoices");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.Product", b =>
                {
                    b.Navigation("saleInvoiceDetails");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.ShopDetail", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("saleInvoices");
                });

            modelBuilder.Entity("Bussiness_Manager.Models.saleInvoice", b =>
                {
                    b.Navigation("saleInvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
